### ISSUE TITLE
[Bug]: missing `yanked_versions` field in `modules/debian_dependency_bazelizer/metadata.json

### ISSUE THREAD

**Issue by xiemotongye** [bazelbuild/bazel-central-registry#1254]
### What happened?

https://registry.bazel.build/ stop updating after this commit:
https://github.com/bazelbuild/bazel-central-registry/commit/83a300d2a31e467ed435da51e53013b8bd6b3730

This commit doesn't contain `yanked_versions` field in `modules/debian_dependency_bazelizer/metadata.json`. This will cause a TypeError in bcr-ui while running npm run build:

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /xxx/bcr-ui/.next/server/chunks/361.js:102:30
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async getStaticPropsModulePage (/xxx/bcr-ui/.next/server/chunks/361.js:98:26)
    at async getStaticProps (/xxx/bcr-ui/.next/server/chunks/361.js:491:12)
    at async renderToHTML (/xxx/bcr-ui/node_modules/next/dist/server/render.js:492:20)
    at async /xxx/bcr-ui/node_modules/next/dist/export/worker.js:253:36
    at async Span.traceAsyncFn (/xxx/bcr-ui/node_modules/next/dist/trace/trace.js:79:20)
```

### Version

Development (host) and target OS/architectures: macOS

Output of `bazel --version`: 6.3.2

Version of relevant rules from the `WORKSPACE` or `MODULE.bazel` file:

Language(s) and/or frameworks involved:

### How to reproduce

```shell
git clone https://github.com/bazel-contrib/bcr-ui
cd bcr-ui
git submodule update --init
cd data/bazel-central-registry
git checkout main
cd -
npm run build
```

**Comment by xiemotongye** [comment]
related to https://github.com/bazel-contrib/bcr-ui/issues/134

**Comment by xiemotongye** [comment]
pr: https://github.com/bazelbuild/bazel-central-registry/pull/1255

**Comment by xiemotongye** [comment]
There is a similar case here:
https://github.com/bazelbuild/bazel-central-registry/pull/850

In order to prevent similar problems from recurring, maybe BCR should improve the metadata validation?
